LoadModule wsgi_module "/home/setup/.local/share/venv/lib/python3.13/site-packages/mod_wsgi/server/mod_wsgi-py313.cpython-313-x86_64-linux-gnu.so"
WSGIPythonHome "/home/setup/.local/share/venv"

ServerName localhost

<VirtualHost "*:80">
    WSGIDaemonProcess code user=setup group=setup python-path="/home/setup/code"
    WSGIScriptAlias /code /home/setup/code/config/wsgi.py
    <Directory /home/setup/code>
        WSGIProcessGroup code
        WSGIApplicationGroup %{GLOBAL}
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    Alias /code/static /home/setup/code/data/static
    <Directory /home/setup/code/data/static>
        Require all granted
    </Directory>
</VirtualHost>
